default: print-args read-file read-file-from-arg extract-words linked-list

print-args: print-args.c
	gcc print-args.c -o print-args.exe

read-file: read-file.c
	gcc read-file.c -o read-file.exe

read-file-from-arg: read-file-from-arg.c
	gcc read-file-from-arg.c -o read-file-from-arg.exe

extract-words: extract-words.c
	gcc extract-words.c -o extract-words.exe

linked-list: linked-list.c
	gcc linked-list.c -o linked-list.exe